### ISSUE TITLE
PNG download transparency wrong?

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/bsbi-atlas-drupal8#18] opened 2023-10-05 16:03 UTC
PNG colour inverted when enlarging plot PNG on twitter.
See https://x.com/sacrevert/status/1709896885312303414?s=20

**Comment by burkmarr** [comment] 2023-10-09 11:07
Rather than inverting the colours, I think that the problem is simply that the background to the chart images is transparent. When Twitter shows the enlarged image it shows it over a black background rather than white. All the black elements on the original image are then invisible - in the example you gave, that's all the elements except the actual bars. The solution is to generate the chart images with a solid white background rather than transparent (as we already do with the map images). It should be an easy fix.

**Comment by burkmarr** [comment] 2023-10-09 14:26
Fixed on live.

**Closed by burkmarr** 2023-10-09 14:26 UTC
